--liquibase formatted sql

--changeset cesar:201809052120
--comment: CREATE ALL TABLES

USE TESTE;

CREATE TABLE LEITOR(
	ID_LEITOR NUMERIC,
    NOME VARCHAR(30),
    EMAIL VARCHAR(100)
);

CREATE TABLE HISTORICO(
	ID_LIVRO NUMERIC,
    ID_LEITOR NUMERIC,
    DATA VARCHAR(10)
);

CREATE TABLE LIVRO(
	ID_LIVRO NUMERIC,
    TITULO VARCHAR(40),
    AUTOR VARCHAR(50),
    EDITORA VARCHAR(50),
    EDICAO VARCHAR(20),
    NUM_PAGINAS VARCHAR(9)
);
--rollback DROP TABLE LEITOR;
--rollback DROP TABLE HISTORICO;
--rollback DROP TABLE LIVRO;