--liquibase formatted sql

--changeset cesar:201809052130
--comment: INSERT REGISTER IN THE TABLE LIVRO
USE TESTE;

INSERT INTO LIVRO VALUES(1,'O NOME DO VENTO', 'PATRICK', 'ARQUEIRO', '1 EDICAO', '350');
INSERT INTO LIVRO VALUES(2,'O TEMOR DO SABIO', 'PATRICK', 'ARQUEIRO', '2 EDICAO', '1000');
INSERT INTO LIVRO VALUES(3,'A MUSICA DO SILENCIO', 'PATRICK', 'ARQUEIRO', '1 EDICAO', '150');
INSERT INTO LIVRO VALUES(4,'JOGADOR NUMERO 1', 'ESCRITOR', 'CULTURA', '10 EDICAO', '475');
INSERT INTO LIVRO VALUES(5,'NARNIA', 'LEWIS', 'CULTURA', '4 EDICAO', '1000');

--rollback DELETE FROM LIVRO;