--liquibase formatted sql

--changeset cesar:201809052127
--comment: INSERT REGISTER IN THE TABLE LEITOR
USE TESTE;

INSERT INTO LEITOR VALUES(1, 'CESAR', 'CESAR.SANTOS@OUTLOOK.COM');
INSERT INTO LEITOR VALUES(2, 'CAROLINA', 'CAROLINA.SANTOS@GMAIL.COM');
INSERT INTO LEITOR VALUES(3, 'BRUNA', 'BRUNA.IGNAT@HOTMAIL.COM');

--rollback DELETE FROM LEITOR;
